version: '2'

volumes:
  postgresql_data:
  ldap_data:
  ldap_config:

services:
  apache:
    build:
      context: ./apache
      dockerfile:  Dockerfile
    image: igeo/apache
    privileged: true
    ports:
     - "10.10.22.103:80:80"
     - "10.10.22.103:443:443"
    
  ldap:
    build:
      context: ./ldap
      dockerfile:  Dockerfile
    image: igeo/ldap
    ports:
     - "389:389"
    environment:
     - SLAPD_ORGANISATION=georchestra
     - SLAPD_DOMAIN=georchestra.org
     - SLAPD_PASSWORD=secret
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap
    volumes:
      - /etc/georchestra:/etc/georchestra

  postgresql:
    build:
      context: ./postgresql
      dockerfile:  Dockerfile
    image: igeo/postgresql
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_USER=dyndb
      - POSTGRES_PASSWORD=dyndb4751_
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  proxycas:
    build:
      context: ./proxycas
      dockerfile:  Dockerfile
    image: igeo/proxycas
    ports:
     - "8080:8080"
     - "8443:8443"
    environment:
     - XMS=256M
     - XMX=1G
    depends_on:
     - ldap
     - postgresql
    volumes:
      - /etc/georchestra:/etc/georchestra

  mapfishapp:
    build:
      context: ./mapfishapp
      dockerfile:  Dockerfile
    image: igeo/mapfishapp
    ports:
     - "8280:8280"
    depends_on:
     - postgresql
    volumes:
      - /etc/georchestra:/etc/georchestra

