version: '2'

volumes:
  postgresql_data:
  ldap_data:
  ldap_config:

services:
  apache:
    build:
      context: ./apache
      dockerfile:  Dockerfile
    image: igeo/apache
    ports:
     - "80:80"
     - "443:443"
    depends_on:
     - proxycas
    
  ldap:
    build:
      context: ./openldap
      dockerfile:  Dockerfile
    image: igeo/ldap
    ports:
     - "389:389"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap
    volumes:
      - /etc/georchestra:/etc/georchestra

  postgresql:
    build:
      context: ./postgresql
      dockerfile:  Dockerfile
    image: igeo/postgresql
    environment:
      - POSTGRES_USER=dyndb
      - POSTGRES_PASSWORD=dyndb4751_
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
     - "5432:5432"

  proxycas:
    build:
      context: ./proxycas
      dockerfile:  Dockerfile
    image: igeo/proxycas
    ports:
     - "8080:8080"
     - "8443:8443"
    depends_on:
     - ldap
     - postgresql
    volumes:
      - /etc/georchestra:/etc/georchestra

